version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 639266140742.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=639266140742.dkr.ecr.$AWS_REGION.amazonaws.com/node-app
      - IMAGE=$REPOSITORY_URI:$IMAGE_TAG
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE .
      - docker tag $IMAGE $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"container-name","imageUri":"%s"}]' $IMAGE > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
